compressionLevel: 0

enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

preferInteractive: true

<<<<<<< HEAD
yarnPath: .yarn/releases/yarn-4.7.0.cjs
=======
yarnPath: .yarn/releases/yarn-4.9.1.cjs
>>>>>>> fb18560061 ([MIRROR] RS pack port and tgui core 3.0.4 (#10638))
