compressionLevel: 0

enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard
<<<<<<< HEAD

pnpEnableEsmLoader: false
=======
  - code: YN0002
    level: discard
    pattern: css-loader@*
  - code: YN0002
    level: discard
    pattern: url-loader@*
>>>>>>> 6a60c4597b ([MIRROR] another tgui update (#10803))

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.7.0.cjs
