# Removes guide comments from PRs when opened, so that when we merge them
# and reuse the pull request description, the clutter is not left behind
name: Remove guide comments
on:
  pull_request_target:
    types: [opened]
jobs:
  remove_guide_comments:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
    - name: Checkout
      uses: actions/checkout@v4
    - name: Remove guide comments
      uses: actions/github-script@v7
      with:
        script: |
          const { removeGuideComments } = await import('${{ github.workspace }}/tools/pull_request_hooks/removeGuideComments.js')
          await removeGuideComments({ github, context })
=======
      - name: Checkout
        uses: actions/checkout@v5
      - name: Remove guide comments
        uses: actions/github-script@v8
        with:
          script: |
            const { removeGuideComments } = await import('${{ github.workspace }}/tools/pull_request_hooks/removeGuideComments.js')
            await removeGuideComments({ github, context })
>>>>>>> 2cf7b5e7f4 (Bump actions/github-script from 7 to 8 (#11567))
